`ifndef YAPP_BASE_SEQ
`define YAPP_BASE_SEQ
  class yapp_base_seq extends uvm_sequence #(yapp_packet);

  `uvm_object_utils(yapp_base_seq)

  function new(string name = "yapp_base_seq");
    super.new(name);
  endfunction


  task body();
	  `uvm_info(get_type_name(),"exec-yapp_base_seq",UVM_LOW)
    repeat (5) begin
      yapp_packet pkt;
      pkt = yapp_packet::type_id::create("pkt");
      `uvm_do(pkt)

    end
  endtask

endclass
`endif

// ------------------------------------------------------------------------------
// 2. Incrementing Address Sequence (0 -> 1 -> 2)
// ------------------------------------------------------------------------------
// a. Inherits from yapp_base_seq for automated objection management
class yapp_012_seq extends yapp_base_seq;

  // c. Factory registration macro
  `uvm_object_utils(yapp_012_seq)

  // c. Standard object constructor
  function new(string name = "yapp_012_seq");
    super.new(name);
  endfunction : new

  task body();
    // b. Informational tracking banner at the very start (UVM_LOW verbosity)
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s", get_type_name()), UVM_LOW)

    // Inline constraint blocks guiding the solver on a per-packet basis
    `uvm_do_with(req, { addr == 0; })
    `uvm_do_with(req, { addr == 1; })
    `uvm_do_with(req, { addr == 2; })
  endtask : body

endclass : yapp_012_seq


// ------------------------------------------------------------------------------
// 3. Single Target Address 1 Sequence
// ------------------------------------------------------------------------------
// a. Inherits from yapp_base_seq for automated objection management
class yapp_1_seq extends yapp_base_seq;

  // c. Factory registration macro
  `uvm_object_utils(yapp_1_seq)

  // c. Standard object constructor
  function new(string name = "yapp_1_seq");
    super.new(name);
  endfunction : new

  task body();
    // b. Informational tracking banner at the very start (UVM_LOW verbosity)
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s", get_type_name()), UVM_LOW)

    // Generates a single transaction strictly targeted to address channel 1
    `uvm_do_with(req, { addr == 1; })
  endtask : body

endclass : yapp_1_seq


// ------------------------------------------------------------------------------
// 4. Simple nested sequence Target Address 1
// ------------------------------------------------------------------------------
// a. Inherits from yapp_base_seq for automated objection management
class yapp_111_seq extends yapp_base_seq;

  // c. Factory registration macro
  `uvm_object_utils(yapp_111_seq)

  // c. Standard object constructor
  function new(string name = "yapp_111_seq");
    super.new(name);
  endfunction : new

  task body();
    // Declare a handle for the child sequence we want to nest
    yapp_1_seq single_seq;
   // Execute the child sequence 3 times in a row
    repeat (3) begin
      // The `uvm_do macro automatically detects that 'single_seq' is a sequence 
      // (not a packet), instantiates it via the factory, and runs it on the current sequencer.
      `uvm_do(single_seq)
    end  
  endtask : body

endclass : yapp_111_seq

// ------------------------------------------------------------------------------
// 5. Repeat Random Address Sequence (Two packets to the same random address)
// ------------------------------------------------------------------------------
//Inherits from yapp_base_seq for automated objection management
class yapp_repeat_addr_seq extends yapp_base_seq;

  //Factory registration macro
  `uvm_object_utils(yapp_repeat_addr_seq)

  //Standard object constructor
  function new(string name = "yapp_repeat_addr_seq");
    super.new(name);
  endfunction : new

  task body();
    // Local variable to store and transfer the first generated address
    bit [1:0] prev_addr;

    //Informational tracking banner at the very start (UVM_LOW verbosity)
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s", get_type_name()), UVM_LOW)

    // Packet 1: Generate a random packet but explicitly restrict it from address 3
    `uvm_do_with(req, { addr != 3; })

    // Capture the randomized address value generated by the solver
    prev_addr = req.addr;

    // Packet 2: Force the next packet to match the captured address exactly
    `uvm_do_with(req, { addr == prev_addr; })
    
  endtask : body

endclass : yapp_repeat_addr_seq

// ------------------------------------------------------------------------------
// 6. Incremental Payload Sequence (Manual item manipulation sequence)
// ------------------------------------------------------------------------------
class yapp_incr_payload_seq extends yapp_base_seq;

  `uvm_object_utils(yapp_incr_payload_seq)

  function new(string name = "yapp_incr_payload_seq");
    super.new(name);
  endfunction : new

  task body();
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s", get_type_name()), UVM_LOW)

    // 1. Create a packet to send
    `uvm_create(req)

    // 2. Randomize the packet (This executes constraints and your post_randomize())
    if (!req.randomize()) begin
      `uvm_fatal("RAND_FAIL", "Failed to randomize packet in yapp_incr_payload_seq")
    end

    // 3. Set the payload values to increment from 0 to length - 1
    foreach (req.payload[i]) begin
      req.payload[i] = i;
    end

    // 4. Update parity manually using your exact class logic
    // Since we mutated the payload array above, the old parity value is wrong.
    if (req.parity_type == GOOD_PARITY) begin
      req.parity = req.calc_parity(); // Use your calculation function directly
    end 
    else begin
      // If the randomizer picked BAD_PARITY, maintain an intentional error
      do begin
        req.parity = $urandom;
      end while (req.parity == req.calc_parity());
    end

    // 5. Send it
    `uvm_send(req)

  endtask : body

endclass : yapp_incr_payload_seq

// ------------------------------------------------------------------------------
// 7. Random Packet Count Sequence (Sequence with its own random properties)
// ------------------------------------------------------------------------------
// a. Inherits from yapp_base_seq for automated objection management
class yapp_rnd_seq extends yapp_base_seq;

  // Declare a random sequence property to control execution loop count
  rand int count;

  // Set an internal constraint to bound the sequence execution scope
  constraint count_limit { count inside {[1:10]}; }

  // c. Factory registration macro
  `uvm_object_utils(yapp_rnd_seq)

  // c. Standard object constructor
  function new(string name = "yapp_rnd_seq");
    super.new(name);
  endfunction : new

  task body();
    // b. Informational tracking banner containing BOTH the name and the random count value
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s | Generating %0d random packets", get_type_name(), count), UVM_LOW)

    // Generate completely random packets according to the solved count value
    repeat (count) begin
      `uvm_do(req)
    end
  endtask : body

endclass : yapp_rnd_seq

// ------------------------------------------------------------------------------
// 8. Random Packet Count to 6 Sequence (Sequence with its own random properties)
// ------------------------------------------------------------------------------
// a. Inherits from yapp_base_seq for automated objection management
class six_yapp_seq extends yapp_base_seq;

  // Declare a random sequence property to control execution loop count
  rand int count;

  // Set an internal constraint to bound the sequence execution scope
  constraint count_limit { count inside {[1:6]}; }

  // c. Factory registration macro
  `uvm_object_utils(six_yapp_seq)

  // c. Standard object constructor
  function new(string name = "six_yapp_seq");
    super.new(name);
  endfunction : new

  task body();
    // b. Informational tracking banner containing BOTH the name and the random count value
    `uvm_info("SEQ_START", $sfmtf("Executing sequence: %s | Generating %0d random packets", get_type_name(), count), UVM_LOW)

    // Generate completely random packets according to the solved count value
    repeat (count) begin
      `uvm_do(req)
    end
  endtask : body

endclass : six_yapp_seq



